export const ERROR_CODE = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_REQUIRED: 'AUTH_TOKEN_REQUIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_UNIQUE_CONSTRAINT: 'DATABASE_UNIQUE_CONSTRAINT',
  DATABASE_RECORD_NOT_FOUND: 'DATABASE_RECORD_NOT_FOUND',
  DATABASE_VALIDATION_ERROR: 'DATABASE_VALIDATION_ERROR',
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR: 'DATABASE_QUERY_ERROR',
  HTTP_EXCEPTION: 'HTTP_EXCEPTION',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INTEGRATION_ERROR: 'INTEGRATION_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
